### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by MarzaElise** [PyTweet/PyTweet#53]
from what i know, the `HTTPClient` class isnt supposed to be used by users. Why does it have docstrings and documented [here](https://github.com/MarzaElise/PyTweet/blob/patch/pytweet/http.py#L148-L181)

**Comment by MarzaElise** [comment]
[here,](https://github.com/MarzaElise/PyTweet/blob/patch/pytweet/http.py#L216-L235) [here,](https://github.com/MarzaElise/PyTweet/blob/patch/pytweet/http.py#L290-L307) [here,](https://github.com/MarzaElise/PyTweet/blob/patch/pytweet/http.py#L330-L347) [here,](https://github.com/MarzaElise/PyTweet/blob/patch/pytweet/http.py#L415-L429)  and many other places

**Comment by MarzaElise** [comment]
Also, why is there a http_client argument in some http methods? couldnt `self` be used in those situations?

**Comment by TheGenocides** [comment]
I have done what you asked. Will push soon!
